filenames_pos = {...
    '9 6-Audio, steady whistling.wav',...
    '10 3-Audio-1,faint drone.wav',...
    '7 4-Audio, about 60 feet-1.wav',...
    '7 5-Audio, about 60 feet-1.wav'...
    '7 6-Audio, about 100 feet-1.wav'};
filenames_neg = {...
    '4 3-Audio-1, speech.wav',...
    '0005 3-Audio, go cart.wav'};

for i = 1:length(filenames_neg)
    
end