clear all;
[y,fs] = audioread('drone_Anechoic_model1.wav');
sampleLength = 4096;
ySignal = y(1:sampleLength,1);
%in_fismat=genfis1(data, mf_n);
%out_fismat = anfis(data, in_fismat, [nan nan ss]);
%estimatedNoise = evalfis(data(:,1:2),out_fismat);
%estimatedSignal = ySignal - estimatedNoise;
T = 1/fs;
t = linspace(1,length(ySignal)/44100,length(ySignal));
L = length(ySignal);
f = fs*((-L/2):(L/2)-1)/L;
figure();
signalTransform = abs(fftshift(fft(ySignal(:,1))));
plot(f/1000,signalTransform);
%plot((ySignal(:,1)));
%plot(ySignal);
xlabel('Frequency (kHz)');
%ylim([0 30]);
xlim([0 22]);
title('Signal');